# Generated by Django 4.0.4 on 2022-06-11 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('subject', models.TextField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 11, 22, 8, 51, 770547, tzinfo=utc), null=True)),
            ],
            options={
                'verbose_name_plural': 'Info',
                'ordering': ['date'],
                'get_latest_by': 'date',
            },
        ),
    ]
