# Generated by Django 4.0.4 on 2022-06-11 22:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 11, 22, 9, 9, 97861, tzinfo=utc), null=True),
        ),
    ]
