# Generated by Django 4.1.5 on 2023-01-29 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_info_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 29, 5, 53, 41, 16954, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
